spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anti_fraud?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000
      pool-name: SpringHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  application:
    name: Anti_fraud
server:
  port: 8090
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: debug
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.anti_fraud.Entity
  global-config:
    db-config:
      id-type: auto
